### ISSUE TITLE
Taobao数据集无法复现出原文的效果

### ISSUE THREAD

**Issue by printf123** [anonymous282828/anonymous_hpmr#1]
感谢你们出色的工作！但我在复现论文时发现，Beibei数据集上可达到接近原文报告的效果，Taobao数据集的效果与原文相差较大，不知是何原因，我已使用代码中推荐的超参数进行实验。

**Comment by MC-CV** [comment]
[log2024-05-14 13:37:19.744160.txt](https://github.com/MC-CV/HPMR/files/15316229/log2024-05-14.13.37.19.744160.txt)
[log2024-05-14 14:54:16.366230.txt](https://github.com/MC-CV/HPMR/files/15316230/log2024-05-14.14.54.16.366230.txt)
[log2024-05-14 15:01:49.234033.txt](https://github.com/MC-CV/HPMR/files/15316231/log2024-05-14.15.01.49.234033.txt)
[log2024-05-14 15:02:58.199305.txt](https://github.com/MC-CV/HPMR/files/15316232/log2024-05-14.15.02.58.199305.txt)

**Comment by MC-CV** [comment]
感谢您的评论，以上是我最近整理代码时跑的4次log文件，均能达到文中的效果（之前在实验的时候是取了均值作为最后的结果，同时进行了假设性检验，结果显著高于最高的baseline）。您的问题可能是：1.tf版本问题，代码tf1.15在3090及以上配置时建议使用nvidia-tensorflow=1.15.4+nv20.10，这个版本。2.需要下载tensorflow-determinism=0.3.0，以便复现使用。最后，再次感谢您的评论。HPMR在工业应用上的价值更高一些，其中的PTN插件可以尝试应用在线上精排、重排阶段，未来我将考虑进一步提升其泛用性，使其能用在更广泛的领域，欢迎关注。
